version: "3.8"
services:
  frontend:
    image: node:20
    container_name: react-vite-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge